export enum ItemQuality {
  Unknown = -1,
  Normal = 0,
  Genuine = 1,
  Rarity2 = 2,
  Vintage = 3,
  Rarity3 = 4,
  Unusual = 5,
  Unique = 6,
  Community = 7,
  Valve = 8,
  SelfMade = 9,
  Customized = 10,
  Strange = 11,
  Completed = 12,
  Haunted = 13,
  Collectors = 14,
  Decorated = 15,
}
