name: API - Production

on: [push, workflow_dispatch]

permissions:
  id-token: write
  contents: read

env:
  AZURE_WEBAPP_NAME: tf2backpackviewer # Set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: "./src/api" # Set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: "9.0.x" # Set this to the dot net version to use

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repo
      - uses: actions/checkout@main
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Run dotnet build and publish
      - name: dotnet build and publish
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release --property:PublishDir='./publish'

      # Deploy to Azure Web apps
      - name: "Run Azure webapp deploy action using publish profile credentials"
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/BackpackViewer.API/publish"

      - name: logout
        run: |
          az logout
